version: '3.8'
services:

    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app

    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"

    database:
        image: mysql:5.7
        container_name: database
        restart: unless-stopped
        volumes:
                - ./dbdata:/var/lib/mysql
        environment:
                - "MYSQL_ROOT_PASSWORD=password"
                - "MYSQL_DATABASE=pet_shop"
        ports:
                - "33063:3306"

